#!/bin/sh
set -e

configure() {
	# Droidian 100: migration to phosh-osk-stub
	runonce-queue droidian-100-phosh-osk-stub 101

	# Droidian 101: chatty desktop file has been renamed
	# during 101 development and it has been renamed back.
	# So there is no change when coming from 100, but
	# we should properly revert for people that were
	# on next.
	runonce-queue droidian-101-chatty-revert 101
}

case "$1" in
	"configure")
		configure
		;;
esac
