#!/bin/bash

# Droidian 100 migrates to phosh-osk-stub from
# squeekboard.
#
# On Droidian 101, the alternative has changed, so
# we need to re-force it again

update-alternatives \
	--set Phosh-OSK /usr/share/phosh-osk-stub/mobi.phosh.OskStub.desktop

# We don't really care if unsuccessful
exit 0
